plugins {
    id 'com.android.application'
}

android {
    namespace "com.example.sdlcross"
    compileSdkVersion 36

    defaultConfig {
        applicationId 'com.example.sdlcross'
        minSdkVersion 21
        targetSdkVersion 33
        versionCode 1
        versionName '1.0'

        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=c++_shared', '-DCMAKE_CXX_STANDARD=20'
                // abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
                abiFilters 'arm64-v8a'
            }
        }
    }

    externalNativeBuild {
        cmake {
            path '../../CMakeLists.txt'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        prefab true
    }
}

task copyWebpLibs(type: Copy) {
    // Clear the target folder before copying to prevent leftover files
    doFirst {
        delete file("src/main/jniLibs/arm64-v8a")
    }

    // Source directory of the built libraries
    from "C:/libs/SDL3_image-devel-3.5.0-android/jniLibs/arm64-v8a"
    include "libwebp.so", "libwebpdemux.so", "libwebpmux.so"
    
    // Target directory
    into "src/main/jniLibs/arm64-v8a"
    
    // Always re-run this task by ignoring the Gradle cache
    outputs.upToDateWhen { false }
}
// Run this copying task before the build starts
preBuild.dependsOn copyWebpLibs

dependencies {
    implementation files('C:/libs/SDL3-devel-3.4.12-android/SDL3-3.4.12.aar')
    implementation files('C:/libs/SDL3_ttf-devel-3.2.2-android/SDL3_ttf-3.2.2.aar')
    implementation files('C:/libs/SDL3_image-devel-3.5.0-android/SDL3_image-3.5.0.aar')

    implementation 'androidx.appcompat:appcompat:1.5.1'
}
